[build]
  command = "hugo mod get -u && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
HUGO_VERSION = "0.139"
HUGO_THEMESDIR = "../.."
HUGO_THEME = "repo"
TZ = "UTC+8"

[context.production.environment]
HUGO_ENV = "production"